language: java
jdk:
- oraclejdk7
script: ant dist
env:
  global:
    secure: hH+ndhQYLCfGaJ8XXW0GW9jO8wv4Ek0tDz3StzyVq9F+6meXOiGFIJ6MCyLPVZouxpCYj03PC0DunWAYYn+e3lgdMeOBLIg6/1BpOs5i0eHImE6O7pdo/+/jsHtR60PG9qRNfw2JXpPTI0F730o4UBi4V2eY2hWfmCIAWj61X9U=
addons:
  coverity_scan:
    project:
      name: martinpaljak/apdu4j
      description: apdu4j
    notification_email: martin@martinpaljak.net
    build_command_prepend: 
    build_command: ant compile
    branch_pattern: coverity
