language: java
sudo: required
jdk:
- oraclejdk8
script: ant dist
notifications:
  email: true
env:
  global:
    secure: hH+ndhQYLCfGaJ8XXW0GW9jO8wv4Ek0tDz3StzyVq9F+6meXOiGFIJ6MCyLPVZouxpCYj03PC0DunWAYYn+e3lgdMeOBLIg6/1BpOs5i0eHImE6O7pdo/+/jsHtR60PG9qRNfw2JXpPTI0F730o4UBi4V2eY2hWfmCIAWj61X9U=

# Scan on Coverity
addons:
  coverity_scan:
    project:
      name: martinpaljak/apdu4j
      description: apdu4j
    notification_email: martin@martinpaljak.net
    build_command_prepend: 
    build_command: ant compile
    branch_pattern: coverity

# Deploy releases to Github.
# Build Windows utility
# See https://github.com/travis-ci/travis-ci/issues/3701
before_deploy:
  - sudo apt-get update
  - sudo apt-get install libc6:i386
  - mkdir -p ext/launch4j
  - curl http://kent.dl.sourceforge.net/project/launch4j/launch4j-3/3.8/launch4j-3.8-linux.tgz | tar xz -C ext
  - ant windist
deploy:
  file:
    - apdu4j.jar
    - apdu4j.exe
    - apdu4j-vanilla.jar
  provider: releases
  api-key:
    secure: kUETLp7FylqzqjmpOdDMwVT3cPecn9gzDyipzuOV7+rL+xjL5ZxeHVNiK2QNRG1pLwih4IRhKQjPHofmUoc0pyLIfz7PjKojdpintBcHXUn7CIMhFMURd6+DmIRIX6HNVXQNd/bF8OOYV+Azfukx5FTUmB9HDbJ6L0BEHO0Dl3E=
  skip_cleanup: true
  on:
    tags: true
