language: java
sudo: false
jdk:
- oraclejdk8
before_script:
- mkdir -p ext
- wget http://kent.dl.sourceforge.net/project/launch4j/launch4j-3/3.12/launch4j-3.12-linux.tgz
- echo "e8f5c546e288bc207a00f06fa01e6124e4f763f4eadccb7ca359071b95f75349  launch4j-3.12-linux.tgz" | sha256sum -c
- tar -C ext -xzf launch4j-3.12-linux.tgz
install: true
script:
- if [ "${COVERITY_SCAN_BRANCH}" == 1 ]; then exit; fi
- mvn clean compile findbugs:check package
- ant windist
env:
  global:
    secure: hH+ndhQYLCfGaJ8XXW0GW9jO8wv4Ek0tDz3StzyVq9F+6meXOiGFIJ6MCyLPVZouxpCYj03PC0DunWAYYn+e3lgdMeOBLIg6/1BpOs5i0eHImE6O7pdo/+/jsHtR60PG9qRNfw2JXpPTI0F730o4UBi4V2eY2hWfmCIAWj61X9U=
addons:
  apt:
    packages:
    - libc6:i386
  coverity_scan:
    project:
      name: martinpaljak/apdu4j
      description: apdu4j
    notification_email: martin@martinpaljak.net
    build_command: mvn clean compile
    branch_pattern: coverity
deploy:
  file:
  - apdu4j.jar
  - apdu4j.exe
  provider: releases
  api-key:
    secure: kH+E1b21G7kd/sRC2AsBH//e5/mR9N0KYrPiR2WpKXCTZUUPcGqn5bq6hpGM9BEct/Q0NPq10xU4xAqfaNbq7UZsQQZ2vFH4Rlhv0mDpY28+ysXrjFROJCZezYf2r0ltc0ZysfPon3LOkfkDkR5t0fw0uLii3Ickj8JQ3ItOUPE=
  skip_cleanup: true
  on:
    tags: true
cache:
  directories:
  - "~/.m2"
